// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © EdiGal

//@version=5
strategy("Candle Absorption #1", overlay=true, initial_capital = 1000)

isCurrentGreen = close >= open
isCurrentRed = not isCurrentGreen

isPreviousGreen = close[1] >= open[1]
isPreviousRed = not isPreviousGreen

isPivotUp = isCurrentGreen and isPreviousRed
isPivotDown = isCurrentRed and isPreviousGreen

curPoints = math.abs(close-open)
prevPoints = math.abs(close[1]-open[1])

isAbsorption = curPoints > prevPoints

isBearishAbsorption = isAbsorption and isPivotUp
isbullishAbsorption = isAbsorption and isPivotDown

if (isBearishAbsorption)
    strategy.entry("Enter Long", strategy.long)
    strategy.exit("Exit Long", from_entry="Enter Long", stop=open)
if(isbullishAbsorption)
    strategy.exit("Exit Long", from_entry="Enter Long", stop=open)